### ISSUE TITLE
#1 Users can view list of National Parks

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#1]
## 💰 Feature

Users can view list of National Parks

## 🗒️ Notes

This will require me to create a home page where users can select view all parks
Will require fetching data from the API in the back-end
Create route for front-end communication

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/102926067-3eb0af00-4449-11eb-9e47-c3335c6c2adb.png)
![image](https://user-images.githubusercontent.com/57933609/102926120-57b96000-4449-11eb-8459-fa35a1de67fb.png)

## ✅ Tasks

- [x] Have font and colors ready
- [x] Create a route in `server/index.js` to handle GET requests at 'api/nationalParks'
- [x] Handle errors
- [x] Test the route with HTTPie.
- [x] Define components for header / main page / footer
- [x] Refactor the component to fetch the data from the server using eventHandler.
- [x] Define components for displaying parks as a list (map)
- [x] Work on displaying one image per park on the list
- [x] Test thoroughly
- [x] Remove any unnecessary code
