### ISSUE TITLE
#9 Users can check whether reviews exist for a particular park (view them if they exist)

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#10]
## 💰 Feature

User can click view reviews to view reviews of that park

## 🗒️ Notes

This will require me to use fetch on the front end 
Create a route in the backend to obtain all reviews for that park
Display as a list

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103432196-15ea9100-4b90-11eb-995a-f7be23864a44.png)
![image](https://user-images.githubusercontent.com/57933609/103432203-28fd6100-4b90-11eb-938d-64596802db15.png)

## ✅ Tasks

- [x] Add button for viewing reviews
- [x] Create a new page for showing reviews
- [x] Create a backend route for getting results from database
- [x] Have the reviews displayed as a list
- [x] Display message if no reviews found
- [x] Test
- [x] Remove any unnecessary code
