### ISSUE TITLE
#11 Users can add parks to the a list of parks which they visited

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#11]
## 💰 Feature

User can mark a park as visited 

## 🗒️ Notes

This will require me to use to add a button which the user can click
The text of the button will change
Will add to the database 

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103568630-c0a5cc80-4e7a-11eb-816a-1ccbcf8fcdc7.png)
![image](https://user-images.githubusercontent.com/57933609/103568655-cd2a2500-4e7a-11eb-9115-7caae1b90c74.png)

## ✅ Tasks

- [x] Fix headers
- [x] Fix button width
- [x] Fix Json stuff
- [x] Add message if no itineraries
- [x] Add button to page
- [x] Add backend route to determine whether it has been visited 
- [x] Render differently based on database query whether it has been visited
- [x] Add back end route for adding visited to database 
- [x] If it has not been visited and user hits button, add to database 
- [x] Test 
- [x] Remove unnecessary code
