### ISSUE TITLE
#12 Users can view the list of parks which they visited

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#12]
## 💰 Feature

User can view a list of the parks they visited

## 🗒️ Notes

This will require me to use a new page which will list all of the parks visited 

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103580520-31ef7a80-4e8f-11eb-87de-eb6fe097950b.png)

## ✅ Tasks

- [x] Add backend route for getting all visited
- [x] Create new page for display 
- [x] Display the info as a list
- [x] Test
