### ISSUE TITLE
#10 Users can view a list of parks which have reviews

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#13]
## 💰 Feature

User can view a list of parks which have reviews

## 🗒️ Notes

This will require me to use a new route for getting a list of parks with reviews 

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103503046-f65d9d80-4e07-11eb-92ea-946d9bc0e9b1.png)

## ✅ Tasks

- [x] Add link after submitting review goes to reviews of that park
- [x] Activate link on nav bar to go to reviews list 
- [x] Create page for reviewed parks
- [x] Add route to back end
- [x] Display as list 
- [x] Add arrow on each item
- [x] When user clicks arrow navigate to park reviews
- [x] Test 
- [x] Remove any unnecessary code
