### ISSUE TITLE
# 2 Users can search for National Parks in each state

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#2]
## 💰 Feature

User can search for National Parks in each state

## 🗒️ Notes

This will require me to use a form for state input
Then adjust the href to reflect the current State

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103104669-646ebd00-45dd-11eb-98dc-f42c65c51159.png)
![image](https://user-images.githubusercontent.com/57933609/103104677-74869c80-45dd-11eb-8c14-609e06997f61.png)

## ✅ Tasks

- [x] Connect button main page to a new page with form
- [x] Create form
- [x] Add a route for obtaining results for one state
- [x] Have the user input be sent over in the request to be included in the url
- [x] Modify heading to include State name (using props passed in)
- [x] Add spinner when data is being fetched (state = isLoading etc)
- [x] Test
- [x] Remove unnecessary code
