### ISSUE TITLE
Issue- User can sign up

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#27]
## 💰 Feature

User can log in

## 🗒️ Notes

This will require me to create a new register page

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103594169-bb617580-4eac-11eb-9cca-c29c05bfbbd5.png)

## ✅ Tasks

- [x] Create page for registering
- [x] Make sure it redirects
- [x] Updated database column names
- [x] Create back end route
- [x] Test
