### ISSUE TITLE
Issue - user can sign in

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#29]
## 💰 Feature

User can sign in

## 🗒️ Notes

This will require me to use a new route and new page

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103598883-9541d280-4eb8-11eb-8f06-ffbf19546701.png)

## ✅ Tasks

- [x] Create a helper method
- [x] Create back-end route
- [x] Create front-end page
- [x] Add the authorization middleware
- [x] Refactor userid to use token
- [x] Test 
- [x] Remove any unnecessary code
