### ISSUE TITLE
#3 Users can view a summary/general weather/photos of each park

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#3]
## 💰 Feature

User can view a tabbed list where they can choose to see summary/general weather/photos

## 🗒️ Notes

This will require me to use a tabbed list
Will also require obtaining the specific data for each park

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103247804-fef03880-491c-11eb-8787-c3bcd9448d20.png)
![image](https://user-images.githubusercontent.com/57933609/103247817-0f081800-491d-11eb-9795-f5e783c288b8.png)
![image](https://user-images.githubusercontent.com/57933609/103247840-1e876100-491d-11eb-886e-a48e814d09f9.png)

## ✅ Tasks

- [x] Update conditionals
- [x] When arrow for a specific park is pressed, add parkCode to url
- [x] Add a new page component for the tabbed list 
- [x] Add a route to the back-end api for parkCode
- [x] In componentDidMount, call the api to fetch he particular park
- [x] Create a tabbed list
- [x] Enter 3 different sections of info
- [x] Make sure the tabs look visually ok (highlighting the displayed tab)
- [x] Test
- [x] Remove unnecessary code
- [x] fix images.length
- [x] remove path from state
- [x] pass path as props
- [x] fix width
- [x] fix back-end to return just the data required
