### ISSUE TITLE
Design Updates

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#38]
## ✅ Tasks

-  [x] All "links" inside buttons should just be links styled like buttons (no buttons for links)
-  [x] The text color for links/button-styled links should be more legible
-  [x] Tame down your light blue color #b1dfe4
-  [x] On larger screens the font size of the park list item titles (park names) should be larger
-  [x] remove all horizontal wiggle
-  [x] refreshing a screen should not switch to a different screen
-  [x] beware very small font sizes (button links on park details page)
-  [x] use consistent border radius and border color
-  [x] List group items that contain link icons should probably just be surround in an anchor tag themselves
-  [x] avoid font sizes smaller than 1 rem, unless you are trying to deliberately downplay the importance of the text
-  [x] favor larger line heights for lists of checkboxes. it's easier to click
