### ISSUE TITLE
#4 Users can view a list of things-to-do at each NP

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#5]
## 💰 Feature

User can view a list of available activities

## 🗒️ Notes

This will require me to use a button to get the the list,
Will require getting this data from the API

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103311922-6b783f80-49d0-11eb-9099-9c4cb5a2edf6.png)
![image](https://user-images.githubusercontent.com/57933609/103311946-7fbc3c80-49d0-11eb-8bd1-3700f4562179.png)

## ✅ Tasks

- [x] Create button for things-to-do
- [x] Create a new page component
- [x] Figure out how to pass the park info, or else call API again
- [x] Work with checkbox to display the list
- [x] Test
- [x] Remove unnecessary code
