### ISSUE TITLE
#5 Users can add items from that list to create an itinerary

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#6]
## 💰 Feature

User can add items from checkbox to create itinerary

## 🗒️ Notes

This will require me to use form submit
Requires database setup for inserting itinerary

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103330713-9043d580-4a17-11eb-89e0-3bc82f0921c8.png)
![image](https://user-images.githubusercontent.com/57933609/103330779-c5e8be80-4a17-11eb-8307-66da472a3bc2.png)

## ✅ Tasks

- [x] Add button on form for submission
- [x] Set up database
- [x] Add dummy data for user
- [x] Add route in backend for database communication
- [x] Deal with submitting the form
- [x] Test
- [x] Remove unnecessary code
- [x] Add returns on promises
- [x] Fix up ParkActivities
