### ISSUE TITLE
#6 Users can view their itineraries

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#7]
## 💰 Feature

User can view a list of itineraries and click on an individual itinerary to view it

## 🗒️ Notes

This will require me to create a new page
Will require getting the data from the database

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103385668-39d6a580-4ab0-11eb-99b4-a93d1eb39dc8.png)
![image](https://user-images.githubusercontent.com/57933609/103385694-51159300-4ab0-11eb-8c1e-d49d9bf1bb19.png)

## ✅ Tasks

- [x] Create page for itineraries
- [x] Get the names of itineraries available from the database 
- [x] Create backend route
- [x] When user clicks an itinerary, get it from the database
- [x] Create new page for displaying itineraries
- [x] Populate page with a list containing all itinerary items
- [x] Test
- [x] Remove unnecessary code
