### ISSUE TITLE
#7 Users can change completed status of item

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#8]
## 💰 Feature

User can change completed status of items on itinerary

## 🗒️ Notes

This will require me to use event handler to update the database

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103423050-6b577b80-4b59-11eb-8732-5a207e8115dc.png)

## ✅ Tasks

- [x] Added sm border
- [x] Add heading for user to check off items
- [x] Set up event handler on each item
- [x] Update the database accordingly
- [x] Test
- [x] Remove any unnecessary code
