### ISSUE TITLE
#8 Users can review their experience in a NP

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/national-park-planner#9]
## 💰 Feature

User can review their experience

## 🗒️ Notes

This will require me to create a review dashboard for that park
Will require adding a button for new reviews

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/57933609/103431141-5fcb7b00-4b80-11eb-8b94-55be0845c97d.png)

![image](https://user-images.githubusercontent.com/57933609/103426050-73b8b200-4b6b-11eb-8655-4fd3f221ef3b.png)

## ✅ Tasks

- [x] Make nav button and button on details scrren go to reviews dashboard
- [x] Create review dashboard with buttons
- [x] Have button "create review" navigate to new page with form
- [x] New review page should have a form for collecting users review
- [x] Handle submit to call back-end api
- [x] Create route for backend to insert into database
- [x] Test
- [x] Remove unnecessary code
- [x] Remove unnecessary conditional and changed setting hash in then block
